description: Updates a changelog if certain labels are set
inputs:
  git_user_email:
    description: Email to associate with commits
    required: true
  git_user_name:
    description: Name to associate with commits
    required: true
name: Changelog Bot
runs:
  image: Dockerfile
  using: docker
