name: Changelog Bot

on:
  pull_request:
    types: [closed]

jobs:
  changelog-bot:
    runs-on: ubuntu-latest
    name: Update CHANGELOG.md
    steps:
      - uses: actions/checkout@v1
      - name: Update Changelog if applicable
        uses: ponylang/changelog-bot-action@0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
